<a href="https://colab.research.google.com/github/asiddiqha/ML_Practice/blob/main/FeatureEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('loan_approved.csv')

category_columns = ['Married', 'Self_Employed', 'Dependents', 'Gender']

for col in category_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

df.isnull().sum()

Loan_ID                    0
Gender                     0
Married                    0
Dependents                 0
Education                  0
Self_Employed              0
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [3]:
## Checking duplicate data

df.duplicated().sum()

np.int64(0)

In [5]:
## Change Data Types just for reference

# df['Age'] = df['Age'].astype('int64')
# df['Age'] = df['Age'].astype('float')
# df['Loan_ID'] = df['Loan_ID'].astype('str')

In [6]:
## Handling incorrect data

df['Gender'] = df['Gender'].str.lower()

In [7]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
## Basic String Cleaning